#!/usr/bin/python


'''
SnakeMake pipeline to run ArrayScan2CNV
'''

import glob
import sys
import os
import shutil
import fnmatch
from snakemake.utils import R


configfile: "config.yaml"


gtc_dir = config['gtc_dir']
gtcFiles = []
SAMPLE_IDS = []
sampIdToGtcDict = {}
for root, dirnames, filenames in os.walk(gtc_dir):
    for filename in fnmatch.filter(filenames, '*.gtc'):
        gtc = os.path.join(root, filename)
        sampId = filename[:-4]
        sampleIds.append(sampId)
        sampIdToGtcDict[sampId] = gtc
        gtcFiles.append(gtc)



def getGtc(wildcards):
    sampId = wildcards.sample_id
    return sampIdToGtcDict[sampId]


rule all:
    input:
        expand('PennCnvIn/{sample_id}.PennCNV_in.txt', sample_id = SAMPLE_IDS)


rule gtc2PennCNV:
    input:
        gtc = getGtc,
        bpm = config['bpm']
    output:
        'PennCnvIn/{sample_id}.PennCNV_in.txt'
    shell:
        'module load python/2.7.5;python gtc2PennCNV.py {input.gtc} {input.bpm} {output}'

